title: Open Educational Resources (OER) in the History of the Book: Towards a New Anthology
description: Remediating the Early Book: Pasts and Futures- MSCA
show_downloads: true
google_analytics:
theme: minima
